###########
# General
###########

# Mouse support (scrolling, selecting panes, etc.)
set -g mouse on

# Move the status bar to the bottom
set-option -g status-position bottom

# Don't rename tabs automatically
set-option -g allow-rename off

# Disable delay on Esc key
set -sg escape-time 0
set -g status-interval 0

# Vim-style copy mode
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'reattach-to-user-namespace pbcopy'

set -g default-command "reattach-to-user-namespace -l /bin/zsh"

################
# Key Bindings
################

# Add prefix mapped to Ctrl + J
set -g prefix2 C-j; bind-key C-j send-prefix -2

# Reload config with Ctrl + R
bind r source-file ~/.tmux.conf

# Switch pane with Ctrl + Arrow Keys
bind -n C-Left select-pane -L
bind -n C-Right select-pane -R
bind -n C-Up select-pane -U
bind -n C-Down select-pane -D

# Switch pane with Ctrl + Arrow Keys
bind -n M-Left select-window -t -1
bind -n M-Right select-window -t +1

# Horizontal split with 
bind h split-window -h
bind v split-window -v

# Clear scrollback with Ctrl + K
bind -n C-k clear-history



#################
# Colour Scheme
#################

# 256 Colours
set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g default-terminal "xterm-256color"

# Panes
set -g pane-border-bg colour0
set -g pane-border-fg colour8
set -g pane-active-border-bg colour0
set -g pane-active-border-fg colour14

# Status Line
set -g status-justify left
set -g status-bg colour0
set -g status-fg colour8
set -g status-interval 2

setw -g window-status-format "#W "
setw -g window-status-current-format "#W "
setw -g window-status-current-fg colour2
setw -g window-status-attr dim

set -g status-left " #S: "
set -g status-right "#{pane_mode}"
