#!/bin/bash

echo "Linking $PWD/nvim to $HOME/.config/nvim"
ln -snf $PWD/nvim $HOME/.config/nvim

echo "Linking $PWD/alacritty to $HOME/.config/alacritty"
ln -snf $PWD/alacritty $HOME/.config/alacritty
